path:
  ckpt_path: "./output/ckpt/ESD"
  log_path: "./output/log/ESD"
  result_path: "./output/result/ESD"
optimizer:
  batch_size: 64
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3

step:
  total_step: 40000
  log_step: 100
  synth_step: 3000
  val_step: 1000
  save_step: 5000
  mist_warm_up_step: 6000

# Stage-2 needs the checkpoint from Stage-1 FS2 to initialize and freeze the encoder
stage1_version: "your_version_name"
stage1_ckpt_step: 20000
